# -*- coding: utf-8 -*-
"""flask1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S32hsC2pKdddC6oQDNL6hMyAwnXUdOUE
"""

!pip install Flask

from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'

if __name__ == '__main__':
    app.run(debug=True)